spring:
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT:database-1-instance-1.c96i6y2g0vfl.eu-north-1.rds.amazonaws.com}:${RDS_PORT:5432}/${RDS_DB_NAME:postgres}?ssl=true&sslmode=require
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:${RDS_AUTH_TOKEN:postgres}}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
