server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://admin:admin123@eureka-server:8761/eureka/}

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 10000s
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
